### ISSUE TITLE
Is this just a pirated copy or is this a reverse engineered/patched program? (EXE)

### ISSUE THREAD

**Issue by Aeyth8** [marcussacana/Bink2#3]
I'm only here for the executable, and I was just curious what/or how is it here?
Like, is it just a copy pasted file that some developer distributed when they worked on a game using Bink2?
Is it just such a simple program that there isn't any licensing checks/etc?

Or if it's just a reverse engineered version that was either patched or completely recreated from scratch.
The encoder works perfectly for me, but I was just wondering if you have the source code and if it's posted anywhere.

- Thanks

**Comment by marcussacana** [comment]
As mentioned in the Git description, "Finally the encoder is public :)", the binaries here are not a leak or piracy. The Bink2 Encoder has officially become public and is now part of Unreal Engine.

The purpose of this repository is to provide a way to access the encoder without needing to download the entire Unreal Engine. This is the first public version of the encoder, which means it supports the oldest public Bink2 format, making it compatible with more games.

The patched version is essentially a 'port' of the API for use with an older game I wanted to modify (Steins;Gate). To clarify, this is not a crack or anything similar. Here's a more detailed explanation:
- The public encoder creates a .bk2 file that older games do not support.
- I needed the older game to read the .bk2 file format.
- I asked myself, who handles the video decoding? The answer is bink2w32.dll.
- My problem: old .dll and new .bk2, which are incompatible with older games.
- My solution: Patch the newer bink2w32.dll functions.

The patch essentially modifies the 'exported' functions of the .dll to match the calling arguments of the older .dll. The result is a 'backport' of the updated bink2w32.dll to the older game. With the encoder in hand, I was able to make the old game play .bk2 files from the updated codec.

I shared the .dlls as a reference for anyone facing a similar issue while trying to mod an older game, but I do not expect them to work without any adjustments. Each game may have different versions of the Bink2 codec, so some modifications might be necessary.

**Comment by Aeyth8** [comment]
Ah I see, I really appreciate your quick response and detailed explanation.

I was just curious to understand since I didn't find Bink2 anywhere, I'm new to reverse engineering and programming and I wanted to encode some .bk2 files to mod a few games that were built with Bink2 **only**.

The bk2s that were output work perfectly for those games, and they're both newer titles.

I looked for Bink2 previously on the official website, and when I emailed them they told me that it was $10,000 for licensing one game, something I don't need or want, so your repository is perfect for my needs.

I however was curious more about the executable, and I apologize if you had explained that but I wanted to clarify:

Is ``Bink2ForUnreal.exe`` the "official" version? Or is it just a port/modification of the original and publicly available Bink1?
Or is it just rewritten from scratch? 

I was just curious about this by the way, and if it was written from scratch are you willing to post the source code for it? And the source code for the bink2w32.dll? It would make things a whole lot easier for anyone who wants to automate it/implement into their codebase.

\- Thanks again

**Comment by marcussacana** [comment]
The patch was made manually with the help of x64dbg and IDA Pro. Since the source code for the .dll is not available, I relied on the semi-public headers. You can access the Bink2 headers by joining the Epic Games GitHub organization, which requires registration on their website. The headers are included in the Unreal Engine source code. Having access to these headers made it easier to identify which parameters had changed, and IDA Pro helped with analyzing the older .dll.

So, unfortunately, I don't have any source code for the .dll to share.

Regarding the Bink2 license, I believe they still sell licenses for developers, but if you're a developer using it with Unreal Engine, it's free. My target audience is modders, so this should not be used for profit. As long as you're not creating and publishing a game, you should be fine using the binaries from here.

**Comment by Aeyth8** [comment]
The executable/encoder was mainly what I was asking about, but thanks for informing me how to find the DLLs, I am already connected to Epic Games and I looked at those headers a bit ago.

And yeah I'm just modding for free

**Comment by marcussacana** [comment]
Yeah, no one has the source I think, maybe if you want just learn about the codec format you can try read the ffmpeg implementation, but I don't remember well if their decoder support just bink1 or 2 as well.
